### ISSUE TITLE
Favor incluir no CI

### ISSUE THREAD

**Issue by 1985epma** [millenacarvalho/grafeno-devops-test#3]
- name: Run SAST  
      uses: anchore/scan-action@v3
      id: scan

**Comment by 1985epma** [comment]
- name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'xxx/xxxxxx' # Substitua com o nome da imagem corretamente
        exit-code: '1' # Opção para falhar na construção se for encontrada uma vulnerabilidade

**Comment by millenacarvalho** [comment]
Obrigada pelas sugestões! Estarei providenciando.
